Minesweeper: Player Class Reference
Player Class Reference
#include <Player.h>
Classes
class BadChc
class BadFlag
class BadMns
class Badrc
class BadRC
class LessTn1
Public Member Functions
Player ()
Player (string n)
string getName ()
void setName ()
void setBrd ()
void getChc (int &rChoice, int &cChoice)
int getRow ()
int getCol ()
int getMine ()
char askFlg ()
void stats (bool win)
float points (bool win)
void setName (string n)
void setBrd (int r, int c, int m)
void autoChc (int &rChoice, int &cChoice)
char autoFlg ()
Public Member Functions inherited from Stats< int >
Stats ()
int points (bool win)
Private Attributes
string name
int row
int col
int mine
int number
float pts
bool invalid
Additional Inherited Members
Protected Member Functions inherited from Stats< int >
int update (string name, bool win)
Protected Attributes inherited from Stats< int >
int point
Static Protected Attributes inherited from Stats< int >
static vector< string > names
static vector< int > wins
static vector< int > losses
Detailed Description
Definition at line 29 of file Player.h.
Constructor & Destructor Documentation
Player() [1/2]
Player::Player () inline
Default constructor for Player class
Definition at line 39 of file Player.h.
Player() [2/2]
Player::Player (string n) inline
string n is passed as a parameter to initialize n
Definition at line 49 of file Player.h.
Member Function Documentation
askFlg()
char Player::askFlg () inline
Definition at line 185 of file Player.h.
Referenced by Game::play().
autoChc()
void Player::autoChc (int & rChoice, int & cChoice) inline
Definition at line 240 of file Player.h.
Referenced by Game::aPlay().
autoFlg()
char Player::autoFlg () inline
Definition at line 246 of file Player.h.
Referenced by Game::aPlay().
getChc()
void Player::getChc (int & rChoice, int & cChoice) inline
Definition at line 142 of file Player.h.
Referenced by Game::play().
getCol()
int Player::getCol () inline
Definition at line 182 of file Player.h.
Referenced by Game::setUp().
getMine()
int Player::getMine () inline
Definition at line 183 of file Player.h.
Referenced by Game::setUp().
getName()
string Player::getName () inline
Definition at line 67 of file Player.h.
Referenced by Game::shoStrt().
getRow()
int Player::getRow () inline
Definition at line 181 of file Player.h.
Referenced by Game::setUp().
points()
float Player::points (bool win) inline
Definition at line 219 of file Player.h.
setBrd() [1/2]
void Player::setBrd () inline
Definition at line 74 of file Player.h.
Referenced by Game::setUp().
setBrd() [2/2]
void Player::setBrd (int r, int c, int m) inline
Definition at line 233 of file Player.h.
setName() [1/2]
void Player::setName () inline
Definition at line 68 of file Player.h.
Referenced by Game::setUp().
setName() [2/2]
void Player::setName (string n) inline
Definition at line 229 of file Player.h.
stats()
void Player::stats (bool win) inline
Definition at line 208 of file Player.h.
Referenced by Game::gmeOver().
Member Data Documentation
col
int Player::col private
Definition at line 33 of file Player.h.
invalid
bool Player::invalid private
Definition at line 36 of file Player.h.
mine
int Player::mine private
Definition at line 33 of file Player.h.
name
string Player::name private
Definition at line 32 of file Player.h.
number
int Player::number private
Definition at line 34 of file Player.h.
pts
float Player::pts private
Definition at line 35 of file Player.h.
row
int Player::row private
Definition at line 33 of file Player.h.
The documentation for this class was generated from the following file:
Player.h