Minesweeper: Ante_Gabrielle_Project_2.cpp File Reference
Ante_Gabrielle_Project_2.cpp File Reference
#include <iostream>
#include <cstdlib>
#include <ctime>
#include <iomanip>
#include <string>
#include <cstring>
#include <fstream>
#include "Game.h"
#include "Cell.h"
Functions
bool reRun ()
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 61 of file Ante_Gabrielle_Project_2.cpp.
References Game::aPlay(), Game::play(), and reRun().
reRun()
bool reRun ()
Definition at line 76 of file Ante_Gabrielle_Project_2.cpp.
Referenced by main().