Minesweeper: Game Class Reference
Game Class Reference
#include <Game.h>
Public Member Functions
Game ()
Game (string n)
Game (string n, string p, int r, int c, int m)
Game (const Game &right)
void shoStrt ()
void setUp ()
void play ()
void aPlay ()
bool gmeOver ()
Protected Attributes
int nrow
int ncol
int nmines
Private Member Functions
void setUp (string p, int r, int c, int m)
Private Attributes
string name
Player player
InBrd inbrd
OutBrd outbrd
int rC
int cC
int diff
GmeBrd * gb
Static Private Attributes
static int gmeCnt = 0
Detailed Description
Definition at line 26 of file Game.h.
Constructor & Destructor Documentation
Game() [1/4]
Game::Game () inline
Definition at line 56 of file Game.h.
Game() [2/4]
Game::Game (string n) inline
Definition at line 66 of file Game.h.
Game() [3/4]
Game::Game (string n, string p, int r, int c, int m) inline
Definition at line 74 of file Game.h.
Game() [4/4]
Game::Game (const Game & right) inline
Definition at line 81 of file Game.h.
References InBrd::celdata(), inbrd, name, ncol, nmines, nrow, GmeBrd::setCol(), GmeBrd::setMine(), and GmeBrd::setRow().
Member Function Documentation
aPlay()
void Game::aPlay () inline
Definition at line 154 of file Game.h.
References Player::autoChc(), Player::autoFlg(), OutBrd::chkClr(), OutBrd::ckFlg(), OutBrd::clear(), OutBrd::dspBrd(), OutBrd::flag(), OutBrd::rdBrd(), OutBrd::reveal(), OutBrd::spcOpn(), and OutBrd::unflag().
Referenced by main().
gmeOver()
bool Game::gmeOver () inline
Definition at line 189 of file Game.h.
References InBrd::dspBrd(), OutBrd::fRemain(), OutBrd::loss(), Player::stats(), and OutBrd::win().
play()
void Game::play () inline
Definition at line 118 of file Game.h.
References Player::askFlg(), OutBrd::chkClr(), OutBrd::ckFlg(), OutBrd::clear(), InBrd::dspBrd(), GmeBrd::dspBrd(), OutBrd::dspBrd(), OutBrd::flag(), Player::getChc(), OutBrd::rdBrd(), OutBrd::reveal(), OutBrd::spcOpn(), and OutBrd::unflag().
Referenced by main().
setUp() [1/2]
void Game::setUp () inline
Definition at line 101 of file Game.h.
References InBrd::addMine(), InBrd::addVal(), InBrd::celdata(), Player::getCol(), Player::getMine(), Player::getRow(), Player::setBrd(), GmeBrd::setCol(), GmeBrd::setMine(), Player::setName(), and GmeBrd::setRow().
setUp() [2/2]
void Game::setUp (string p, int r, int c, int m) inline private
Definition at line 36 of file Game.h.
References InBrd::addMine(), InBrd::addVal(), InBrd::celdata(), Player::getCol(), Player::getMine(), Player::getRow(), Player::setBrd(), GmeBrd::setCol(), GmeBrd::setMine(), Player::setName(), and GmeBrd::setRow().
shoStrt()
void Game::shoStrt () inline
Definition at line 94 of file Game.h.
References Player::getName().
Member Data Documentation
cC
int Game::cC private
Definition at line 32 of file Game.h.
diff
int Game::diff private
Definition at line 33 of file Game.h.
gb
GmeBrd* Game::gb private
Definition at line 35 of file Game.h.
gmeCnt
int Game::gmeCnt = 0 static private
Definition at line 34 of file Game.h.
inbrd
InBrd Game::inbrd private
Definition at line 30 of file Game.h.
Referenced by Game().
name
string Game::name private
Definition at line 28 of file Game.h.
Referenced by Game().
ncol
int Game::ncol protected
Definition at line 54 of file Game.h.
Referenced by Game().
nmines
int Game::nmines protected
Definition at line 54 of file Game.h.
Referenced by Game().
nrow
int Game::nrow protected
Definition at line 54 of file Game.h.
Referenced by Game().
outbrd
OutBrd Game::outbrd private
Definition at line 31 of file Game.h.
player
Player Game::player private
Definition at line 29 of file Game.h.
rC
int Game::rC private
Definition at line 32 of file Game.h.
The documentation for this class was generated from the following file:
Game.h