Minesweeper: OutBrd Class Reference
OutBrd Class Reference
#include <OutBrd.h>
Public Member Functions
OutBrd ()
void rdBrd (InBrd &a)
void reveal (int r, int c)
void flag (int r, int c)
void unflag (int r, int c)
bool spcOpn (int r, int c)
bool loss (int r, int c)
bool win (int r, int c)
bool ckFlg (int r, int c)
bool chkClr (int r, int c)
void clear (int r, int c)
int fRemain ()
virtual void dspBrd ()
Public Member Functions inherited from GmeBrd
GmeBrd ()
GmeBrd (int r, int cl, int m)
~GmeBrd ()
int getRow () const
int getCol () const
int getMine () const
void setRow (int a)
void setCol (int a)
void setMine (int a)
Private Attributes
Cell ** cell
Additional Inherited Members
Static Protected Attributes inherited from GmeBrd
static int row
static int col
static int mine
Detailed Description
Definition at line 22 of file OutBrd.h.
Constructor & Destructor Documentation
OutBrd()
OutBrd::OutBrd () inline
Definition at line 29 of file OutBrd.h.
Member Function Documentation
chkClr()
bool OutBrd::chkClr (int r, int c)
Definition at line 59 of file OutBrd.cpp.
Referenced by Game::aPlay(), and Game::play().
ckFlg()
bool OutBrd::ckFlg (int r, int c) inline
Definition at line 77 of file OutBrd.h.
References GmeBrd::c, cell, and Cell::getFlgd().
Referenced by Game::aPlay(), and Game::play().
clear()
void OutBrd::clear (int r, int c)
Definition at line 70 of file OutBrd.cpp.
Referenced by Game::aPlay(), and Game::play().
dspBrd()
void OutBrd::dspBrd () virtual
Implements GmeBrd.
Definition at line 20 of file OutBrd.cpp.
Referenced by Game::aPlay(), and Game::play().
flag()
void OutBrd::flag (int r, int c) inline
Definition at line 37 of file OutBrd.h.
References GmeBrd::c, cell, and Cell::setFlgd().
Referenced by Game::aPlay(), and Game::play().
fRemain()
int OutBrd::fRemain () inline
Definition at line 82 of file OutBrd.h.
References cell, GmeBrd::col, GmeBrd::mine, and GmeBrd::row.
Referenced by Game::gmeOver().
loss()
bool OutBrd::loss (int r, int c)
Definition at line 47 of file OutBrd.cpp.
Referenced by Game::gmeOver().
rdBrd()
void OutBrd::rdBrd (InBrd & a)
Definition at line 15 of file OutBrd.cpp.
References InBrd::c.
Referenced by Game::aPlay(), and Game::play().
reveal()
void OutBrd::reveal (int r, int c) inline
Definition at line 34 of file OutBrd.h.
References GmeBrd::c, cell, and Cell::setHddn().
Referenced by Game::aPlay(), and Game::play().
spcOpn()
bool OutBrd::spcOpn (int r, int c) inline
Definition at line 43 of file OutBrd.h.
References GmeBrd::c, and cell.
Referenced by Game::aPlay(), and Game::play().
unflag()
void OutBrd::unflag (int r, int c) inline
Definition at line 40 of file OutBrd.h.
References GmeBrd::c, cell, and Cell::setFlgd().
Referenced by Game::aPlay(), and Game::play().
win()
bool OutBrd::win (int r, int c) inline
Definition at line 58 of file OutBrd.h.
References cell, GmeBrd::col, GmeBrd::getMine(), and GmeBrd::row.
Referenced by Game::gmeOver().
Member Data Documentation
cell
Cell** OutBrd::cell private
Definition at line 25 of file OutBrd.h.
Referenced by ckFlg(), flag(), fRemain(), reveal(), spcOpn(), unflag(), and win().
The documentation for this class was generated from the following files:
OutBrd.h
OutBrd.cpp